name: Minify JavaScript

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Assure que les tags et les branches sont récupérés

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Terser
      run: npm install terser -g

    - name: Minify JavaScript
      run: terser wishlist.js -o wishlist.min.js --compress --mangle

    - name: Commit and push changes if needed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout main # S'assure que nous sommes sur la branche main
        git add wishlist.min.js
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Minify wishlist.js automatically"
          git push origin main
        fi
